#!/bin/sh

export COSMOPOLITAN_DISABLE_ZIPOS=1
export BASELOC="${BASELOC:-$(realpath "$PWD")}"
export COSMO="${COSMO:-$BASELOC/cosmopolitan}"
export COSMOS_X86_64="${COSMOS_X86_64:-$BASELOC/cosmos/x86_64}"
export COSMOS_AARCH64="${COSMOS_AARCH64:-$BASELOC/cosmos/aarch64}"
export RESULTS="${RESULTS:-$BASELOC/results}"
export ZIPCOPY="${ZIPCOPY:-$COSMOCC/bin/zipcopy}"
export APELINK_BIN="${APELINK_BIN:-$COSMOCC/bin/apelink}"
export HOSTARCH="${HOSTARCH:-$(uname -m)}"
export RENAMESTR="${RENAMESTR:-$COSMO/o/$HOSTARCH/tool/build/renamestr}"
